#task
task: "P3"

#subjects to analyse
subjects_numbers: 
  - "002"
  - "019"
  - "037"

#execution mode
isOverwrite: False #overwrite all existing data units with newly generated ones
isDialogeMode: False #manual mode with opens dialogs windows for example for manual cleaning
isPrecomputeMode: True #if TRUE: from step 04 on use precomputed semester project data 

# Band-pass filter limits
#according to https://mne.tools/dev/auto_tutorials/preprocessing/plot_40_artifact_correction_ica.html
bandpass_fmin: 0.5  # Hz
bandpass_fmax: 50  # Hz
nr_filt_cycles: 1 #nr of filter cycles

#peak-to-peak reject criteria in ^-6 scaling
reject_subject_config:  {"002": 200,
                         "019": 200,
                         "037": 200}

# ICA
nr_ica_components: 20
ica_method: "picard"
freq_highpass_ica: 0.1
subject_ica_channels: {"002": [2, 10],
                       "019": [1],
                       "037": [0]}

# Event coding
event_coding: {
    "rare": [11, 22, 33, 44, 55],
    "frequent": [12, 13, 14, 15, 21, 23, 24, 25, 31, 32, 34, 35, 41, 42, 43, 45, 51, 52, 53, 54],
    "response": [201, 202]
}
