#task
task: "P3"

#electrode to pick
pick: "Pz"

#subjects to analyse
subjects_numbers: 
  - "002"
  - "019"
  - "037"

#execution mode
isOverwrite: False #overwrite all existing data units with newly generated ones
isDialogeMode: False #manual mode with opens dialogs windows for example for manual cleaning
isPrecomputeMode: True #if TRUE: from step 04 on use precomputed semester project data 
isSpaceSaveMode: False #When true deletes the .fif of the last step after it was processed --> Save disk space

# Band-pass filter limits
bandpass_fmin: 0.5  # Hz
bandpass_fmax: 50  # Hz
nr_filt_cycles: 1 #nr of filter cycles

#peak-to-peak reject criteria in ^-6 scaling
reject_subject_config:  200

# ICA
nr_ica_components: 20
ica_method: "picard"

#according to https://mne.tools/dev/auto_tutorials/preprocessing/plot_40_artifact_correction_ica.html
freq_highpass_ica: 1
subject_ica_channels: {"002": [1, 9],
                       "019": [1],
                       "037": [0]}

#Reference
reference: ["P9", "P10"]


# Event coding
event_coding: {
    "cond1": [11, 22, 33, 44, 55], #rare
    "cond2": [12, 13, 14, 15, 21, 23, 24, 25, 31, 32, 34, 35, 41, 42, 43, 45, 51, 52, 53, 54], #frequent
    "response": [201, 202] #correct response, wrong reponse --> Order is important here for my functions
}
event_names: {
    "cond1": "rare",
    "cond2": "frequent"
}

# ERP significance testing
alpha: 0.05
peak_window: [0.3, 0.6] #[tmin, tmax] time window for peak finding in grand average peak analysis


#Time-frequency Analysis

#Decoding Analysis
t_start: 0.0
t_end: 1.0
t_sample: 0.05